// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/bookings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "List bookings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Booking"
                            }
                        }
                    }
                }
            }
        },
        "/api/concerts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "concerts"
                ],
                "summary": "List concerts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Concert"
                            }
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Login and get JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/notifications": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Notification"
                            }
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.LoginRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "http.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "model.Booking": {
            "type": "object",
            "properties": {
                "concert_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "description": "pending / confirmed / rejected",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.Concert": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "дата создания записи",
                    "type": "string"
                },
                "date": {
                    "description": "дата проведения",
                    "type": "string"
                },
                "id": {
                    "description": "уникальный идентификатор концерта",
                    "type": "integer"
                },
                "location": {
                    "description": "место проведения",
                    "type": "string"
                },
                "organizer_email": {
                    "description": "e-mail организатора",
                    "type": "string"
                },
                "ticket_price": {
                    "description": "цена одного билета",
                    "type": "number"
                },
                "tickets_left": {
                    "description": "оставшиеся билеты",
                    "type": "integer"
                },
                "tickets_total": {
                    "description": "общее количество билетов",
                    "type": "integer"
                },
                "title": {
                    "description": "название концерта",
                    "type": "string"
                },
                "updated_at": {
                    "description": "дата обновления записи",
                    "type": "string"
                }
            }
        },
        "model.Notification": {
            "type": "object",
            "properties": {
                "concert_id": {
                    "description": "ID концерта",
                    "type": "integer"
                },
                "id": {
                    "description": "уникальный идентификатор уведомления",
                    "type": "integer"
                },
                "sent_at": {
                    "description": "дата и время отправки",
                    "type": "string"
                },
                "status": {
                    "description": "success / failed",
                    "type": "string"
                },
                "user_id": {
                    "description": "ID пользователя",
                    "type": "integer"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "ссылка на аватар",
                    "type": "string"
                },
                "created_at": {
                    "description": "когда создан профиль",
                    "type": "string"
                },
                "email": {
                    "description": "адрес электронной почты",
                    "type": "string"
                },
                "first_name": {
                    "description": "имя",
                    "type": "string"
                },
                "id": {
                    "description": "уникальный идентификатор пользователя",
                    "type": "integer"
                },
                "last_name": {
                    "description": "фамилия",
                    "type": "string"
                },
                "phone": {
                    "description": "номер телефона",
                    "type": "string"
                },
                "updated_at": {
                    "description": "когда обновлён профиль",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go Study API",
	Description:      "CRUD API for users, concerts, bookings, notifications.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
