basePath: /
definitions:
  http.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  http.LoginResponse:
    properties:
      token:
        type: string
    type: object
  model.Booking:
    properties:
      concert_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      status:
        description: pending / confirmed / rejected
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  model.Concert:
    properties:
      created_at:
        description: дата создания записи
        type: string
      date:
        description: дата проведения
        type: string
      id:
        description: уникальный идентификатор концерта
        type: integer
      location:
        description: место проведения
        type: string
      organizer_email:
        description: e-mail организатора
        type: string
      ticket_price:
        description: цена одного билета
        type: number
      tickets_left:
        description: оставшиеся билеты
        type: integer
      tickets_total:
        description: общее количество билетов
        type: integer
      title:
        description: название концерта
        type: string
      updated_at:
        description: дата обновления записи
        type: string
    type: object
  model.Notification:
    properties:
      concert_id:
        description: ID концерта
        type: integer
      id:
        description: уникальный идентификатор уведомления
        type: integer
      sent_at:
        description: дата и время отправки
        type: string
      status:
        description: success / failed
        type: string
      user_id:
        description: ID пользователя
        type: integer
    type: object
  model.User:
    properties:
      avatar_url:
        description: ссылка на аватар
        type: string
      created_at:
        description: когда создан профиль
        type: string
      email:
        description: адрес электронной почты
        type: string
      first_name:
        description: имя
        type: string
      id:
        description: уникальный идентификатор пользователя
        type: integer
      last_name:
        description: фамилия
        type: string
      phone:
        description: номер телефона
        type: string
      updated_at:
        description: когда обновлён профиль
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: CRUD API for users, concerts, bookings, notifications.
  title: Go Study API
  version: "1.0"
paths:
  /api/bookings:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Booking'
            type: array
      summary: List bookings
      tags:
      - bookings
  /api/concerts:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Concert'
            type: array
      summary: List concerts
      tags:
      - concerts
  /api/login:
    post:
      consumes:
      - application/json
      description: Login and get JWT token
      parameters:
      - description: Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/http.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login
      tags:
      - auth
  /api/notifications:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Notification'
            type: array
      summary: List notifications
      tags:
      - notifications
  /api/users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: List users
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
